title: Weiyu Yao's Homepage
page-top-title: Weiyu Yao
top-section-bg-text: Not limited by the past, nor confined to this moment.
home-subtitle: Weiyu Yao&ensp;|&ensp;姚卫宇
copyright-text: '&copy; Weiyu Yao 2025. All Rights Reserved.'
email: "yaoweiyu@sjtu.edu.cn"